T6846: pr title check updated

diff --git a/.github/workflows/check-pr-message.yml b/.github/workflows/check-pr-message.yml
--- a/.github/workflows/check-pr-message.yml
+++ b/.github/workflows/check-pr-message.yml
@@ -33,24 +33,40 @@
           run: |
             source_pr_title=$(gh pr view "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --json title -q .title)
             echo "source_pr_title=$source_pr_title"
-            # ./reusable-actions/scripts/check-pr-title-and-commit-messages.py ${{ github.event.pull_request.url }} ${{ secrets.PAT }}
-            # output=$(./reusable-actions/scripts/check-pr-title-and-commit-messages.py '${{ github.event.pull_request.url }}' '${{ secrets.PAT }}' 2>&1 || true)
-            # if [ -n "$output" ]; then
-            #   echo "$output"
-            #   echo "error_message=${output//$'\n'/. }" >> $GITHUB_ENV         
-            #   exit 1
-            # else
-            #   #echo "error_message=" >> $GITHUB_ENV
-            #   echo "error_message=No issues in PR Title / Commit Title" >> $GITHUB_ENV
-            # fi
+            title_regex='^(([a-zA-Z0-9\-_.]+:\s)?)T\d+:\s+[^\s]+.*'
+            if [[ ! $source_pr_title =~ $title_regex ]]; then
+              echo "PR title '$source_pr_title' does not match the required format!"
+              echo "error_message=PR title does not match the required format" >> $GITHUB_ENV
+              echo "Valid title example: T99999: make IPsec secure"
+              exit 1
+            fi
+            echo "PR title '$source_pr_title' is valid."
+            echo "error_message=No issues in PR Title / Commit Title" >> $GITHUB_ENV
           shell: bash
 
-        # - name: Add PR comment
-        #   if: always()
-        #   uses: mshick/add-pr-comment@v2
-        #   with:
-        #     message: |-
-        #       ${{ env.error_message == 'No issues in PR Title / Commit Title' && '👍' || '❌' }}
-        #       ${{ env.error_message }}
-        #     message-id: "TITLE_COMMIT_VALIDATION"
-        #     allow-repeats: false
+        - name: Check commit messages
+          timeout-minutes: 2
+          id: check_commit_messages
+          run: |
+            commit_regex='^(([a-zA-Z0-9\-_.]+:\s)?)T\d+:\s+[^\s]+.*'
+            commits=$(gh pr view "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --json commits -q '.commits[].commit.message')
+            for commit_message in $commits; do
+              if [[ ! $commit_message =~ $commit_regex ]]; then
+                echo "Commit message '$commit_message' does not match the required format!"
+                echo "error_message=Commit message does not match the required format!" >> $GITHUB_ENV
+                echo "Valid commit message example: T99999: make IPsec secure"
+                exit 1
+              fi
+            done
+            echo "All commit messages are valid."
+            echo "error_message=No issues in PR Title / Commit Title" >> $GITHUB_ENV
+
+        - name: Add PR comment
+          if: always()
+          uses: mshick/add-pr-comment@v2
+          with:
+            message: |-
+              ${{ env.error_message == 'No issues in PR Title / Commit Title' && '👍' || '❌' }}
+              ${{ env.error_message }}
+            message-id: "TITLE_COMMIT_VALIDATION"
+            allow-repeats: false
