T6846: pr title fix

diff --git a/.github/workflows/check-pr-message.yml b/.github/workflows/check-pr-message.yml
--- a/.github/workflows/check-pr-message.yml
+++ b/.github/workflows/check-pr-message.yml
@@ -24,54 +24,34 @@
           with:
             repository: vyos/.github
             path: reusable-actions
-
-        - name: Set up Python
-          uses: actions/setup-python@v5
-          with:
-            python-version: '3.11'
-  
-        - name: Set execute permissions for the script
-          run: |
-            chmod +x reusable-actions/scripts/regex_check.py
   
         - name: Check the PR title
           timeout-minutes: 2
           run: |
-            # ls -ltr reusable-actions/scripts
             source_pr_title=$(gh pr view "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --json title -q .title)
             echo "source_pr_title=$source_pr_title"
             if echo "$source_pr_title" | grep -Pq '^(([a-zA-Z0-9\-_.]+:\s)?)T\d+:\s+[^\s]+.*'; then
                 echo "PR title '$source_pr_title' is valid."
+                echo "error_message=No issues in PR Title / Commit Title" >> $GITHUB_ENV
+            else
+                echo "PR title '$source_pr_title' does not match the required format!"
                 echo "error_message=PR title does not match the required format" >> $GITHUB_ENV
                 echo "Valid title example: T99999: make IPsec secure"
                 exit 1
-            else
-                echo "PR title '$source_pr_title' does not match the required format!"
-                echo "error_message=No issues in PR Title / Commit Title" >> $GITHUB_ENV
             fi
-            # output=$(python reusable-actions/scripts/regex_check.py -i '$source_pr_title' -r '^(?:[a-zA-Z0-9\-_.]+: )?T\d+: .+')
-            # echo "output=$output"
-            # if [ "$output" == "false" ]; then
-            #   echo "PR title '$source_pr_title' does not match the required format!"
-            #   echo "error_message=PR title does not match the required format" >> $GITHUB_ENV
-            #   echo "Valid title example: T99999: make IPsec secure"
-            #   exit 1
-            # fi
-            # echo "PR title '$source_pr_title' is valid."
-            # echo "error_message=No issues in PR Title / Commit Title" >> $GITHUB_ENV
         
         - name: Check commit messages
           timeout-minutes: 2
           run: |
             commits=$(gh pr view "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --json commits -q '.commits[].commit.message')
             for commit_message in $commits; do
-              output=$(python reusable-actions/scripts/regex_check.py -i '$commit_message' -r '^(([a-zA-Z0-9\-_.]+:\s)?)T\d+:\s+[^\s]+.*')
-              echo "output=$output"
-              if [ "$output" == "false" ]; then
-                echo "Commit message '$commit_message' does not match the required format!"
-                echo "error_message=Commit message does not match the required format!" >> $GITHUB_ENV
-                echo "Valid commit message example: T99999: make IPsec secure"
-                exit 1
+              if echo "$commit_message" | grep -Pq '^(([a-zA-Z0-9\-_.]+:\s)?)T\d+:\s+[^\s]+.*'; then
+                  echo "Commit message '$commit_message' is valid."
+              else
+                  echo "Commit message '$commit_message' does not match the required format!"
+                  echo "error_message=PR title does not match the required format" >> $GITHUB_ENV
+                  echo "Valid commit message example: T99999: make IPsec secure"
+                  exit 1
               fi
             done
             echo "All commit messages are valid."
